x-veld:
  executable:
    about:
      description: >
        "Converts NER json data to spacy docbin, and prepares it for training by splitting it into 
        train, dev, eval subsets, and shuffling them randomly."
      scope:
        - "ETL"
        - "NLP"
        - "Machine Learning"
    input:
      a:
        path: "/veld/input/data.json"
        format: "json"
        kind:
          - "Gold Data"
          - "NLP Gold Data"
          - "Named Entity Recognition Gold Data"
        description: >
          "The json data needs to be in a format like: 
          [
            {
              'text_raw': 'Turing was born in London.', 
              'entities': [(0, 6, 'PER'), (19, 25, 'LOC')]
            },
            ...
          ]"
      b:
        environment variables:
          train:
            description: "percentage of data to be used as train data. Defaults to 80."
            optional: true
          dev:
            description: "percentage of data to be used as dev data. Defaults to 10."
            optional: true
          eval:
            description: "percentage of data to be used as eval data. Defaults to 10."
            optional: true
          seed:
            description: "A seed for randomizing the data but keeping it stable across executions. Defaults to 42."
            optional: true
    output:
      a:
        path: "/veld/output/a/"
        format: "Spacy DocBin"
        kind:
          - "Gold Data"
          - "NLP Gold Data"
          - "Named Entity Recognition Gold Data"
      b:
        path: "/veld/output/b/"
        format: "txt"
        kind: "log"

services:
  veld:
    build: .
    volumes:
      - ./src/:/veld/executable/
    environment:
      train: 80
      dev: 10
      eval: 10
      seed: 42
    command: bash -c "python /veld/executable/convert.py |& tee /veld/output/b/convert.log"

