x-veld:
  executable:
    about:
      description: >
        "Converts NER json data to spacy docbin, and prepares it for training by splitting it into 
        train, dev, eval subsets, and shuffling them randomly."
      content:
        - "ETL"
        - "NLP"
        - "Machine Learning"
    input:
      a:
        type: "files"
        format: "json"
        content:
          - "Gold Data"
          - "NLP Gold Data"
          - "Named Entity Recognition Gold Data"
        path: /veld/input/data.json
        description: >
          "The json data needs to be in a format like: 
          [
            {
              'text_raw': 'Turing was born in London.', 
              'entities': [(0, 6, 'PER'), (19, 25, 'LOC')]
            },
            ...
          ]"
      b:
        type: "environment variable"
        name: "train" 
        optional: true
        default: 80
      c:
        type: "environment variable"
        name: "dev" 
        optional: true
        default: 10
      d:
        type: "environment variable"
        name: "eval" 
        optional: true
        default: 10
      e:
        type: "environment variable"
        name: "seed" 
        optional: true
        default: 42
    output:
      a:
        type: "folder"
        format: "Spacy DocBin"
        content:
          - "Gold Data"
          - "NLP Gold Data"
          - "Named Entity Recognition Gold Data"
        path: /veld/output/a/
      b:
        type: "files"
        format: "txt"
        content: "log"
        path: /veld/output/b/convert.log

services:
  veld:
    build: .
    volumes:
      - ./convert.py:/veld/executable/convert.py
    environment:
      train: 80
      dev: 10
      eval: 10
      seed: 42
    command: bash -c "python /veld/executable/convert.py |& tee /veld/output/b/convert.log"

