#x-veld:
#  executable:
#    # TODO: describe CLI paramaters as input too
#    input:
#      path: "/veld/input/"
#      format: "json"
#      kind:
#        - "Gold Data"
#        - "Named Entity Recognition Gold Data"
#    output:
#      1:
#        path: "/veld/output/1/"
#        format: "Spacy DocBin"
#        kind:
#          - "Gold Data"
#          - "Named Entity Recognition Gold Data"
#      2:
#        path: "/veld/output/2/"
#        format: "log"
#    scope:
#      - "ETL"

services:
  veld:
    build: .
    volumes:
      - ./:/veld/executable/
    command: bash -c "python /veld/executable/convert.py |& tee /veld/output/2/convert.log"
    environment:
      train: 80
      dev: 10
      eval: 10
      seed: 42
