x-veld:
  executable:
    about:
      description: ""
      scope:
        - "ETL"
        - "NLP"
        - "Machine Learning"
    input:
      "1":
        path: "/veld/input/data.json"
        format: "json"
        kind:
          - "Gold Data"
          - "NLP Gold Data"
          - "Named Entity Recognition Gold Data"
      "2":
        environment variables:
          train:
            description: "percentage of data to be used as train data. Defaults to 80."
            optional: true
          dev:
            description: "percentage of data to be used as dev data. Defaults to 10."
            optional: true
          eval:
            description: "percentage of data to be used as eval data. Defaults to 10."
            optional: true
          seed:
            description: "A seed for randomizing the data but keeping it stable across executions. Defaults to 42."
            optional: true
    output:
      "1":
        path: "/veld/output/1/"
        format: "Spacy DocBin"
        kind:
          - "Gold Data"
          - "NLP Gold Data"
          - "Named Entity Recognition Gold Data"
      "2":
        path: "/veld/output/2/"
        format: "txt"
        kind: "log"

services:
  veld:
    build: .
    volumes:
      - ./src/:/veld/executable/
    environment:
      train: 80
      dev: 10
      eval: 10
      seed: 42
    command: bash -c "python /veld/executable/convert.py |& tee /veld/output/2/convert.log"

